frontend

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,19 +60,25 @@ jobs:
       - name: Checkout frontend repository
         run: git clone https://github.com/hackathon-Rosbank/rosbank-frontend.git frontend
 
+      # Ensure the frontend directory exists
+      - name: Verify frontend directory exists
+        run: |
+          if [ ! -d "./frontend" ]; then echo "Error: Directory ./frontend does not exist."; exit 1; fi
+
       - uses: actions/checkout@v3
-        # Set up Node.js for frontend
+
+      # Set up Node.js for frontend
       - name: Set up Node.js for frontend
         uses: actions/setup-node@v3
         with:
           node-version: '18'
 
-        # Install frontend dependencies
+      # Install frontend dependencies
       - name: Install frontend dependencies
         run: npm install
         working-directory: ./frontend
 
-        # Build frontend
+      # Build frontend
       - name: Build frontend
         run: npm run build
         working-directory: ./frontend
