frontend

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,26 +31,26 @@ jobs:
 
 #####################################   BACKEND   ####################################
 
-  build_and_push_to_docker_hub:
-    name: Push Docker image to DockerHub
-    runs-on: ubuntu-latest
-    needs: tests
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-      - name: Login to Docker
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      - name: Push to DockerHub
-        uses: docker/build-push-action@v4
-        with:
-          context: ./backend
-          push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/ros_bank_backend:latest
+#  build_and_push_to_docker_hub:
+#    name: Push Docker image to DockerHub
+#    runs-on: ubuntu-latest
+#    needs: tests
+#    steps:
+#      - name: Check out the repo
+#        uses: actions/checkout@v3
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v2
+#      - name: Login to Docker
+#        uses: docker/login-action@v2
+#        with:
+#          username: ${{ secrets.DOCKER_USERNAME }}
+#          password: ${{ secrets.DOCKER_PASSWORD }}
+#      - name: Push to DockerHub
+#        uses: docker/build-push-action@v4
+#        with:
+#          context: ./backend
+#          push: true
+#          tags: ${{ secrets.DOCKER_USERNAME }}/ros_bank_backend:latest
 
   frontend_tests:
     runs-on: ubuntu-latest
@@ -63,7 +63,7 @@ jobs:
       # Ensure the frontend directory exists
       - name: Verify frontend directory exists
         run: |
-          if [ ! -d "./frontend" ]; then echo "Error: Directory ./frontend does not exist."; exit 1; fi
+          if [ ! -d "frontend" ]; then echo "Error: Directory ./frontend does not exist."; exit 1; fi
 
       - uses: actions/checkout@v3
 
@@ -113,7 +113,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs:
-      - build_and_push_to_docker_hub
+#      - build_and_push_to_docker_hub
       - build_frontend_and_push_to_docker_hub
     steps:
       - name: Executing remote ssh commands to deploy
